// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-hackathons.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var list_hackathons_default = defineTool({
  name: "list_hackathons",
  title: "List hackathons",
  description: "List approved, publicly listed hackathons on Hackverse. Supports optional text search and a result limit.",
  inputSchema: {
    query: z.string().trim().optional().describe("Optional case-insensitive substring to match against title, organizer, or country."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return. Default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("hackathons").select("id, title, organizer, country, city, mode, start_date, end_date, prize_pool, registration_url, tags, featured, status").eq("status", "approved").order("start_date", { ascending: true }).limit(limit ?? 20);
    if (query) {
      const like = `%${query}%`;
      q = q.or(`title.ilike.${like},organizer.ilike.${like},country.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { hackathons: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-hackathon.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_hackathon_default = defineTool2({
  name: "get_hackathon",
  title: "Get hackathon",
  description: "Fetch full details for a single approved hackathon by its id.",
  inputSchema: { id: z2.string().uuid().describe("Hackathon id (uuid).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("hackathons").select("*").eq("id", id).eq("status", "approved").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Hackathon not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { hackathon: data }
    };
  }
});

// src/lib/mcp/tools/list-my-submissions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_my_submissions_default = defineTool3({
  name: "list_my_submissions",
  title: "List my submissions",
  description: "List the signed-in user's hackathon submissions with status and reference id.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("hackathon_submissions").select("id, reference_id, event_name, organizer, status, rejection_reason, published_hackathon_id, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { submissions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-submission.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var create_submission_default = defineTool4({
  name: "create_submission",
  title: "Submit a hackathon",
  description: "Create a new hackathon submission on behalf of the signed-in user. Enters the moderation queue with status 'pending'.",
  inputSchema: {
    event_name: z3.string().trim().min(2).describe("Event title."),
    organizer: z3.string().trim().min(1).describe("Organizing team or company."),
    email: z3.string().email().describe("Contact email."),
    description: z3.string().trim().optional(),
    website: z3.string().url().optional(),
    location: z3.string().trim().optional(),
    format: z3.enum(["online", "in-person", "hybrid"]).optional(),
    prize_pool: z3.string().trim().optional(),
    start_date: z3.string().optional().describe("ISO date (YYYY-MM-DD)."),
    end_date: z3.string().optional().describe("ISO date (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const reference_id = `HV-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
    const { data, error } = await supabase.from("hackathon_submissions").insert({
      user_id: ctx.getUserId(),
      reference_id,
      status: "pending",
      ...input
    }).select("id, reference_id, status").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Submission received. Reference ${data.reference_id}, status ${data.status}.` }],
      structuredContent: { submission: data }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_my_profile_default = defineTool5({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in Hackverse user's profile (display name, avatar).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient5(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("profiles").select("id, display_name, avatar_url").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            { user_id: ctx.getUserId(), email: ctx.getUserEmail(), profile: data },
            null,
            2
          )
        }
      ],
      structuredContent: { user_id: ctx.getUserId(), email: ctx.getUserEmail(), profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fctcllatikygnsemygrf";
var mcp_default = defineMcp({
  name: "hackverse-mcp",
  title: "Hackverse",
  version: "0.1.0",
  instructions: "Tools for Hackverse, a global hackathon discovery platform. Browse approved hackathons, view details, and (as the signed-in user) list your own submissions, submit new events, or read your profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_hackathons_default, get_hackathon_default, list_my_submissions_default, create_submission_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
